// Code generated by MockGen. DO NOT EDIT.
// Source: user_problem_service.go

// Package cqrsService is a generated GoMock package.
package cqrsService

import (
	cqrsDto "diff-problems/usecase/cqrs_dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserProblemService is a mock of UserProblemService interface.
type MockUserProblemService struct {
	ctrl     *gomock.Controller
	recorder *MockUserProblemServiceMockRecorder
}

// MockUserProblemServiceMockRecorder is the mock recorder for MockUserProblemService.
type MockUserProblemServiceMockRecorder struct {
	mock *MockUserProblemService
}

// NewMockUserProblemService creates a new mock instance.
func NewMockUserProblemService(ctrl *gomock.Controller) *MockUserProblemService {
	mock := &MockUserProblemService{ctrl: ctrl}
	mock.recorder = &MockUserProblemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProblemService) EXPECT() *MockUserProblemServiceMockRecorder {
	return m.recorder
}

// FindByUserId mocks base method.
func (m *MockUserProblemService) FindByUserId(arg0 string) (cqrsDto.UserProblem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", arg0)
	ret0, _ := ret[0].(cqrsDto.UserProblem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockUserProblemServiceMockRecorder) FindByUserId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockUserProblemService)(nil).FindByUserId), arg0)
}
