name: Check the source code
on: [push]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install
      - name: Prettier
        run: yarn prettier --write src/**/*.{tsx,ts}
#      - name: Lint
#        run: npm run lint
