name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache
      uses: actions/cache@v3.0.1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18  
        
        
  build:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: test
      run: pwd
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
