name: Infra

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-diff-problems
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test
